### ISSUE TITLE
User input

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/RegscorePy#10]
If it's possible to reduce the number of parameters the user has to enter, always do so. For example it's unnecessary to have the user enter "n", the number of data points, as that can be derived from the dimensions of X. If you think there might be edge cases where n != X.shape[0], consider setting n as a named parameter with sensible defaults and allowing the user to overwrite those defaults when necessary.

**Comment by simrnsethi** [comment]
Thanks. This issue has been taken care of in the latest release.
