### ISSUE TITLE
Feedback: Python2/3 bug

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/RegscorePy#37]
In python3:
```bash
>>> from RegscorePy import *
>>> y = [1,2,3,4]
>>> y_pred = [5,6,7,8]
>>> y_sub = [1,2,3,5]
>>> k = 3
>>> p = 2
>>> mallow.mallow(y, y_pred, y_sub, k, p)
0.015625
>>>
```

However, in python2:
```
>>> from RegscorePy import *
>>> y = [1,2,3,4]
>>> y_pred = [5,6,7,8]
>>> y_sub = [1,2,3,5]
>>> k = 3
>>> p = 2
>>> mallow.mallow(y, y_pred, y_sub, k, p)
0
>>>
```

This is because of the different ways python2 and python3 handle integer division. Be sure to cast one of your integers to float() to fix this bug. Also specify in the readme which python version you have tested your package on. On the plus side, your tests failed in the appropriate places when I ran them in python2 so well done :)

**Comment by rq1995** [comment]
In python2, if we run `from __future__ import division` before the function, we will get the correct division. We will include it in README. Thanks.
