### ISSUE TITLE
Feedback: Variable name

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/RegscorePy#39]
Naming a variable 'mallow' within a function named 'mallow' is bad practice. You'll run into weird bugs during development due to choosing a variable name that is the same as a function name.

**Comment by simrnsethi** [comment]
@vmasrani Are you referring to naming our functions the same as function file names? For e.g., in python, you'll have to call `aic.aic`, `bic.bic` and `mallow.mallow` in order to run these functions.

**Comment by rq1995** [comment]
Thanks for remind. I already changed the variable mallow to mallowcp. We can make a distinction between now.
