### ISSUE TITLE
User input models

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/RegscorePy#8]
Your proposed functions take in the data, train a model, and return a metric. However, they don't allow a user to input their own models which is functionality most, if not all, users will want. Your functions also don't return the underlying trained model, so if the users were to find a model that was well-fit to the data there would have no way to access it.

**Comment by simrnsethi** [comment]
Thanks. We have taken care of this issue by redefining the function which now allows the user to input the observed and the predicted values from a trained model and outputs the score. The user can now decide which model to keep and use our function to compare the performance of different models.
